global:
  scrape_interval: 5s

scrape_configs:
  - job_name: feedhandler-coinbase
    static_configs:
      - targets: ["host.docker.internal:9101"]

  - job_name: feedhandler-binance
    static_configs:
      - targets: ["host.docker.internal:9102"]

  - job_name: bookservice
    static_configs:
      - targets: ["host.docker.internal:9103"]

  - job_name: persister
    static_configs:
      - targets: ["host.docker.internal:9104"]

  - job_name: wspublisher
    static_configs:
      - targets: ["host.docker.internal:9105"]